### ISSUE TITLE
Fail on write logs/reports due to user restrictions on workdir

### ISSUE THREAD

**Issue by devdrops** [ricardotulio/docker-magento#7]
Noticed yesterday: when Magento fires up a report/log, the file is not being generated due to lack of permissions on the workdir `/var/www` (I've executed a `chmod 777 -R /var/www/var` to check these files), as defined in the `docker-compose.yml` below:

```yaml
magento:
    image: ricardotulio/magento:master
    env_file: .env
    volumes:
        - .:/opt/docker/magento/module/
    working_dir: /var/www
    ports:
        - "80:80"
```
